name: Build and Publish Python Package and Executables

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pyinstaller py2app

    - name: Build package
      run: python -m build

    - name: Build Windows executable
      run: |
        pyinstaller --onefile batteryCalculator.py
        mv dist/batteryCalculator batteryCalculator.exe

    - name: Build macOS application
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app
      - name: Build macOS app
        run: |
          python setup.py py2app
          mv dist/batteryCalculator.app batteryCalculator.app

    - name: Upload Windows .exe to GitHub Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: batteryCalculator.exe
        asset_name: batteryCalculator.exe
        asset_content_type: application/octet-stream

    - name: Upload macOS .app to GitHub Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: batteryCalculator.app
        asset_name: batteryCalculator.app
        asset_content_type: application/x-apple-diskimage

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
