name: Build and Publish (Windows Only)

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest  # Der Job läuft nur auf Windows

    steps:
    - uses: actions/checkout@v4  # Checkt das Repository aus

    - name: Set up Python
      uses: actions/setup-python@v5  # Richtiges Setup der Python-Version
      with:
        python-version: '3.10'  # Du kannst die Version anpassen, falls nötig

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pyinstaller  # Installiere PyInstaller und andere Abhängigkeiten

    - name: Build package
      run: |
        pyinstaller --onefile batteryCalculator.py  # Erzeuge eine .exe-Datei aus deinem Python-Skript

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/batteryCalculator.exe  # Pfad zur erstellten .exe-Datei
        asset_name: batteryCalculator-${{ github.event.release.tag_name }}.exe  # Name des hochgeladenen Assets
        asset_content_type: application/octet-stream
