name: Build and Publish Windows Executable

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4  # Verwende die neueste Version von setup-python
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pyinstaller

    - name: Build Windows executable
      run: |
        pyinstaller --onefile batteryCalculator.py
        # Ensure the output executable is in the correct folder
        mkdir -p dist/windows
        mv dist/batteryCalculator.exe dist/windows/

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: dist/windows/batteryCalculator.exe
